[project]
name = "ViCLIP-OT"
version = "0.1.5"
description = "ViCLIP-OT: The First Foundation Vision-Language Model for Vietnamese Image–Text Retrieval with Optimal Transport"
readme = "README.md"
license = "GPL-3.0"
requires-python = ">=3.12"
authors = [
  {name = "Minh-Thien Nguyen", email = "minhnguyent546@gmail.com"},
  {name = "Quoc-Khang Tran", email = "twkan2001@gmail.com"},
]
dependencies = [
    "loguru>=0.7.3",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "tqdm>=4.67.1",
    "torch==2.9.1",
    "torchvision==0.24.1",
    "wandb>=0.23.1",
    "pillow>=11.2.1",
    "pyyaml>=6.0.3",
    "matplotlib>=3.10.8",
    "scienceplots>=2.1.1",
    "fvcore>=0.1.5.post20221221",
    "timm>=1.0.24",
    "numpy>=1.24,<2.4",
    "transformers>=4.57.1,<4.58.0",
    "tokenizer>=3.6.2",
    "sentence-transformers>=5.1.0,<5.2.0",
    "huggingface-hub>=0.36.0",
    "sentencepiece>=0.2.1",
    "pydantic>=2.12.5",
    "safetensors>=0.7.0",
    "pot[backend-torch]>=0.9.6.post1",
    "open-clip-torch>=3.3.0",
    "nvidia-ml-py>=13.0.0",
]

[project.urls]
Homepage = "https://github.com/minhnguyent546/ViCLIP-OT"
Repository = "https://github.com/minhnguyent546/ViCLIP-OT"

[dependency-groups]
dev = [
    "ruff>=0.12.10",
    "hf-transfer>=0.1.9",
    "colorama>=0.4.6",
    "tabulate>=0.9.0",
    "einop>=0.0.1",
    "ipykernel>=7.1.0",
    "peft>=0.18.1",
    "qwen-vl-utils>=0.0.14",
    "ipywidgets>=8.1.8",
    "notebook>=7.6.2",
    "jupyterlab>=4.6.3",
    "jupyter-collaboration>=5.0.0",
]
vllm = [
    "vllm==0.16.0",
]
flash-attn = [
    "flash-attn",
]
jina-training = [
    "flash-attn",
    "xformers==0.0.33.post2",
]

[tool.uv]
no-build-isolation-package = ["flash-attn"]

[tool.ruff]
line-length = 99
target-version = "py312"
exclude = [
    "./thirdparty/",
    "./notebooks/",
    "./scripts/qwen3_vl_embedding.py",
    "./scripts/compute-embeddings/qwen3_vl_embedding.py"
]

[tool.ruff.lint]
select = [
    "B",      # flake8-bugbear
    "C",      # comple-structure
    "E",      # pycodestyle errors
    "F",      # pyflakes
    "I",      # isort
    "W",      # pycodestyle warnings
    "RUF013", # implicit-optional
    "UP006",  # non-pep585-annotation (e.g. `list[int]` instead of `List[int]`)
]
extend-safe-fixes = ["UP006"]
ignore = [
    "C901", # complex-structure
    "E101", # mixed-spaces-and-tabs
    "E501", # line-too-long
    "E741", # ambiguous-variable-name
    "F402", # import-shadowed-by-loop-var
    "F823", # undefined-local
]

[tool.ruff.lint.isort]
known-third-party = ["wandb"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "E402", # module-import-not-at-top-of-file
    "F401", # unused-import
    "F403", # undefined-local-with-import-star
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.uv.sources]
flash-attn = [
    { group = "flash-attn", url = "https://huggingface.co/datasets/minhnguyent546/flash-attn-v2.8.3-glibc-2.31/resolve/68b35e77a6899b3670d5d7c29b6f42b6b6edbd95/flash_attn-2.8.3+cu12torch2.9cxx11abiTRUE-cp312-cp312-linux_x86_64.whl" },
    { group = "jina-training", url = "https://huggingface.co/datasets/minhnguyent546/flash-attn-v2.8.3-glibc-2.31/resolve/68b35e77a6899b3670d5d7c29b6f42b6b6edbd95/flash_attn-2.8.3+cu12torch2.9cxx11abiTRUE-cp312-cp312-linux_x86_64.whl" },
]
