#### 2026-01-14_09-22-39-cliploss_dinov3_gemma300m_openviic_final_30

image_config:
  model_name: timm/vit_base_patch14_reg4_dinov2.lvd142m
  pretrained: true
  pool: avg
  proj: linear # low-resource
  proj_bias: false
  proj_dropout_rate: 0.1

text_config:
  model_name: google/embeddinggemma-300m
  proj: none
  proj_bias: false

embed_dim: 768
