image_config:
  model_name: timm/vit_large_patch16_dinov3.lvd1689m
  pretrained: true
  pool: avg
  proj: linear # low-resource
  proj_bias: false
  proj_dropout_rate: 0.1

text_config:
  model_name: keepitreal/vietnamese-sbert
  proj: linear
  proj_bias: false

embed_dim: 1024
